/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * VoxSigil Schema Version 1.8-holo-omega. This master specification defines a fully accountable, globally deployable, and self-sustaining cognitive ecosystem. It incorporates the comprehensive profiles of previous versions and extends them with 33 new top-level properties focused on operational robustness, including observability, sustainability, auditability, accessibility, and advanced compliance controls. Core goal: Propel Vanta (Vanta Orchestration eXpression Symbolic Interface for Generative, Integrated Logic) to its 'holo-omega' vision. This schema distinguishes key concepts: 'Sigil' (the primary ID), 'Tag(s)' (classifiers), 'Pglyph' (a Sigil type representing unique identity/persona, like '⟠∆∇𓂀'), and 'Scaffold' (a Sigil's foundational architectural role).
 */
export interface Voxsigil18HoloOmega {
  /**
   * The primary, globally unique symbolic identifier for this VoxSigil definition. This is the 'Sigil' itself – the fundamental key (e.g., Unicode string '🔮', custom glyph representation '⟠∆∇𓂀', or unique ASCII name 'VANTA_CORE_REASONER_V4.0'). It represents a discrete cognitive component, process, concept, entity, data structure, policy, or abstract construct within the Vanta ecosystem. A 'Pglyph' (Personal/Persona Glyph) is a specialized type of Sigil primarily used to denote the unique identity of an agent or human participant. Must be unique within the entire Vanta sigil library.
   */
  sigil: string;
  /**
   * Canonical, human-readable name for the entity defined by this Sigil (e.g., 'Dream Weaver Prime', 'Marc_Prime_Identity_Construct', 'Echo Concordance Protocol').
   */
  name: string;
  /**
   * Optional alternate name, well-known identifier, or previous version's sigil string. Can associate a 'Pglyph' term if the main 'sigil' field is more abstract (e.g., if 'sigil: AGENT_MARC_ID_001', then 'alias: Marc.pglyph_Operational').
   */
  alias?: string;
  /**
   * Optional primary high-level 'Tag' or keyword used for broad categorization (e.g., 'MemoryComponent', 'ReasoningStrategy', 'IdentityConstruct', 'ArchitecturalScaffold'). This helps Vanta orchestrate and understand sigils at a high level.
   */
  tag?: string;
  /**
   * Optional list of additional 'Tags' or keywords for fine-grained classification. A 'Pglyph' Sigil like '⟠∆∇𓂀' might have tags: ['HumanCollaboratorProfile', 'IdentityCore']. A 'Scaffold' Sigil might be tagged ['VantaCoreFramework', 'CognitiveArchitectureModule']. Examples: ['temporal_processing', 'llm_dependent', 'neuro_inspired', 'self_modifying', 'pglyph_type_agent', 'scaffold_memory_system'].
   */
  tags?: string[];
  /**
   * Indicates if this Sigil represents a foundational, often irreducible, cognitive operation or conceptual building block. Primitives are often referenced by 'Scaffold' Sigils.
   */
  is_cognitive_primitive?: boolean;
  /**
   * If 'is_cognitive_primitive' is true, classifies its fundamental type (e.g., 'categorization', 'analogy_formation', 'value_assignment'). This helps define the very base of Vanta's cognitive functions, often utilized by 'Scaffold' components.
   */
  cognitive_primitive_type?: string;
  /**
   * The core cognitive, philosophical, theoretical, or functional grounding of the sigil. Explains its fundamental meaning, purpose, 'essence,' and intended role in the Vanta ecosystem.
   */
  principle: string;
  /**
   * Optional mathematical, logical, algorithmic, or formal notation (e.g., pseudo-code, lambda calculus expression, state transition equations, probability distribution) representing the sigil's operation, structure, or underlying formalisms.
   */
  math?: string;
  /**
   * Optional references (e.g., paper citations, theory names, framework sigil_refs like 'IWMT_Framework_Sigil') to the scientific or philosophical theories underpinning this sigil's design.
   */
  theoretical_basis_refs?: string[];
  /**
   * Optional symbolic breakdown of composite glyphs, internal structural relationships, or sub-component architecture, especially if this sigil represents a complex entity or process.
   */
  structure?: {
    /**
     * Describes the compositional logic or relationship between sub-elements if this is a composite sigil.
     */
    composite_type?:
      | "sequential"
      | "hierarchical"
      | "parallel"
      | "conditional"
      | "recursive"
      | "network"
      | "fusion"
      | "assembly"
      | "collection"
      | "state_machine"
      | "event_driven_orchestration"
      | "data_processing_pipeline"
      | "feedback_control_loop";
    /**
     * Optional. Describes temporal dynamics, sequencing, or lifecycle of components/operations within this sigil.
     */
    temporal_structure?:
      | "static_config"
      | "sequential_phased_execution"
      | "parallel_concurrent_tracks"
      | "closed_feedback_loop"
      | "open_feedback_loop"
      | "oscillatory_dynamic"
      | "event_triggered_sequence"
      | "continuous_streaming_process"
      | "adaptive_temporal_scaling";
    /**
     * A list of components, sub-elements, or functional blocks that constitute this sigil's internal structure.
     */
    components?: {
      /**
       * Name of the internal component.
       */
      name: string;
      /**
       * Description of the component's role, nature, or function within this sigil.
       */
      description: string;
      /**
       * Optional reference to another fully defined sigil if this component is itself a Vanta sigil (promotes modularity and reuse).
       */
      sigil_ref?: string;
      /**
       * High-level type of this component (e.g., 'input_validator', 'memory_buffer', 'reasoning_kernel', 'output_formatter', 'sensory_transducer').
       */
      component_type_tag?: string;
      /**
       * If sigil_ref is used, JSON string specifying overrides for the referenced sigil's parameters in this specific context.
       */
      parameters_override_json?: string;
      /**
       * Order in which this component is initialized if part of a sequence.
       */
      initialization_sequence_order?: number;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Describes how the sigil is used in practice within the Vanta system, by other sigils, or by human interactors.
   */
  usage: {
    /**
     * A concise summary of what the sigil does or represents in practical application within Vanta.
     */
    description: string;
    /**
     * A concrete example of the sigil in use: a text snippet (prompt, system call, thought process), a Vanta orchestration script segment, or a structured object detailing a scenario with inputs and expected outcomes.
     */
    example?:
      | string
      | {
          [k: string]: unknown;
        };
    /**
     * A more detailed explanation of its application, typical context, interactions with other sigils/components, expected impact, or implications of its use in Vanta workflows.
     */
    explanation?: string;
    /**
     * [v1.7] For sigils exposed as microservices, this is a reference to a Sigil defining its public API endpoint (e.g., OpenAPI spec), authentication, and rate limits.
     */
    api_endpoint_and_schema_ref?: string;
    [k: string]: unknown;
  };
  /**
   * Defines conditions, assumptions, and prerequisites for when and how this sigil should be activated or applied by the Vanta orchestration logic.
   */
  activation_context?: {
    /**
     * Specific scenarios, Vanta system events or logical expressions that warrant this sigil's activation.
     */
    triggering_events_or_conditions?: string[];
    /**
     * Explicit conditions or state requirements that must be met before activation.
     */
    preconditions_state_refs?: string[];
    /**
     * Internal or external resources/capabilities this sigil needs to function.
     */
    required_capabilities_self?: string[];
    /**
     * Cognitive, functional, or resource capabilities the activating Vanta agent/subsystem must possess to effectively use this sigil.
     */
    required_capabilities_activator?: string[];
    /**
     * Specific input modalities this sigil can process.
     */
    supported_modalities_input?: (
      | "text_structured"
      | "text_natural_language"
      | "audio_speech_transcribed"
      | "audio_ambient_features"
      | "image_raw"
      | "image_semantic_segments"
      | "video_stream_raw"
      | "video_object_tracking"
      | "haptic_signal_encoded"
      | "olfactory_cue_signature"
      | "symbolic_data_stream"
      | "physiological_data_timeseries"
      | "programmatic_api_call"
      | "multi_modal_fused_embedding"
      | "vanta_event_bus_message"
    )[];
    /**
     * Specific output modalities this sigil can generate.
     */
    supported_modalities_output?: (
      | "text_formatted_report"
      | "text_natural_dialogue"
      | "generated_speech_synthesized"
      | "spatial_audio_ambisonic"
      | "image_generated_static"
      | "video_generated_stream"
      | "haptic_feedback_pattern_id"
      | "olfactory_release_command"
      | "symbolic_data_structure"
      | "programmatic_api_response"
      | "multi_modal_fused_output"
      | "vanta_orchestration_command"
    )[];
    /**
     * Situations, contexts, or input types where this sigil should NOT be applied, or known failure conditions/edge cases.
     */
    contraindications_or_failure_modes?: string[];
    /**
     * A descriptive rule or reference to a Vanta orchestration policy that determines this sigil's priority if multiple sigils are triggered simultaneously.
     */
    activation_priority_logic?: string;
    [k: string]: unknown;
  };
  /**
   * Defines optional parameters that can configure or customize this sigil's behavior at runtime or during instantiation by Vanta orchestration.
   */
  parameterization_schema?: {
    parameters?: {
      /**
       * Parameter name.
       */
      name: string;
      type:
        | "string"
        | "number"
        | "integer"
        | "boolean"
        | "enum"
        | "sigil_ref"
        | "json_object_stringified"
        | "array_of_strings"
        | "array_of_numbers"
        | "data_stream_id_ref"
        | "regex_pattern_string"
        | "vanta_policy_ref";
      /**
       * Controls and impact description.
       */
      description: string;
      /**
       * Optional default value. Must conform to 'type'.
       */
      default_value?: {
        [k: string]: unknown;
      };
      /**
       * Lists allowed literal values or sigil_refs.
       */
      allowed_values_or_refs?: unknown[];
      value_range?: {
        min?: number;
        max?: number;
        step?: number;
        [k: string]: unknown;
      };
      is_required_for_operation?: boolean;
      validation_rules_description?: string;
      mutability?: "immutable_post_init" | "runtime_adjustable" | "evolvable_by_system";
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Canonical prompt structure for LLM invocation, potentially orchestrated by Vanta. Central to generative logic. Can be fully defined inline or reference a 'PromptTemplateSigil'.
   */
  prompt_template?: {
    definition_type: "inline_definition" | "reference_to_prompt_template_sigil";
    /**
     * If definition_type is 'reference_to_prompt_template_sigil', this is the sigil_ref to the PromptTemplateSigil.
     */
    prompt_template_sigil_ref?: string;
    /**
     * LLM role for this prompt segment. Required for inline.
     */
    role?:
      | "system_orchestrator"
      | "user_simulator"
      | "assistant_core_logic"
      | "tool_input_formatter"
      | "tool_output_parser"
      | "internal_reflector";
    /**
     * Inline prompt template content. Can reference fragments using {{fragment_id_from_fragments_refs}} or variables using {{variable_name}}. Required for inline.
     */
    content?: string;
    /**
     * Applicable for inline.
     */
    execution_mode?:
      | "command_dispatch"
      | "query_resolution"
      | "reflective_analysis"
      | "emergent_simulation"
      | "task_decomposition"
      | "data_transformation"
      | "creative_generation"
      | "critical_evaluation"
      | "information_extraction"
      | "instruction_following"
      | "tool_invocation_request"
      | "dialogue_continuation"
      | "world_interaction_simulation_step"
      | "self_correction_suggestion";
    /**
     * Variables used in the inline content template.
     */
    variables?: {
      name: string;
      description: string;
      example?: string;
      required_for_llm?: boolean;
      /**
       * e.g., 'json_string', 'list_of_concepts', 'code_block'
       */
      type_hint?: string;
      [k: string]: unknown;
    }[];
    /**
     * Expected output format from inline prompt: JSON schema reference (sigil_ref to schema definition), or natural language description.
     */
    output_schema_ref_or_description?:
      | string
      | {
          [k: string]: unknown;
        };
    /**
     * Guidance for the LLM or Vanta's LLM orchestration layer related to this inline prompt.
     */
    notes_for_llm_or_orchestrator?: string;
    /**
     * LLM-specific parameters like temperature, max_tokens for THIS inline prompt.
     */
    invocation_parameters?: {
      temperature?: number;
      max_output_tokens?: number;
      stop_sequences?: string[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Optional prompt for invoking an inverse, reflective, or debugging operation. Can be inline or reference a 'PromptTemplateSigil'.
   */
  inverse_prompt_template?: {
    definition_type?: "inline_definition" | "reference_to_prompt_template_sigil";
    prompt_template_sigil_ref?: string;
    [k: string]: unknown;
  };
  /**
   * List of sigil_refs to reusable 'PromptFragmentSigil' definitions. These sigils would contain fragment_id, content, description, roles_applicable, variables_used.
   */
  prompt_fragments_refs?: string[];
  /**
   * Defines meaningful semantic, operational, or orchestration relationships with other sigils in the Vanta ecosystem.
   */
  relationships?: {
    target_sigil_ref: string;
    relationship_type:
      | "depends_on_output_of"
      | "prerequisite_for_activation_of"
      | "enables_functionality_in"
      | "extends_capabilities_of"
      | "generalizes_concept_of"
      | "is_composed_of_instance"
      | "is_component_of_system"
      | "synergizes_with_operation_of"
      | "conflicts_with_goal_of"
      | "is_alternative_implementation_for"
      | "is_analogous_to_concept_in"
      | "is_inverse_operation_of"
      | "triggers_activation_of"
      | "uses_method_from_interface"
      | "instantiates_archetype_of"
      | "specifies_configuration_for"
      | "is_derived_from_version"
      | "monitors_state_of"
      | "provides_grounding_data_for"
      | "co_evolves_with_definition_of"
      | "simulates_behavior_described_by"
      | "is_instance_of_metasigil"
      | "collaborates_with_human_role_defined_by"
      | "receives_input_from"
      | "sends_output_to"
      | "is_orchestrated_by"
      | "provides_ethical_oversight_for"
      | "reports_telemetry_to"
      | "is_antagonistic_to"
      | "provides_computational_resource_for";
    /**
     * Explanation of this specific relationship instance.
     */
    description?: string;
    /**
     * Relative strength, importance, or priority of this relationship.
     */
    strength_or_priority?: number;
    /**
     * The Vanta operational context in which this relationship is most relevant.
     */
    context_of_relationship?: string;
    /**
     * JSON string of parameters to use when interacting with target_sigil_ref in this relationship.
     */
    parameters_for_target_interaction_json?: string;
    [k: string]: unknown;
  }[];
  /**
   * Links to analogous concepts, theories, or terminology in other disciplines or external knowledge bases.
   */
  cross_domain_tags?: {
    /**
     * e.g., 'CognitivePsychology', 'Neuroscience', 'ControlTheory', 'LiteraryTheory', 'Sociology'.
     */
    domain: string;
    /**
     * The analogous term or concept in that domain.
     */
    term: string;
    /**
     * Optional URI to a definition or reference for the term.
     */
    term_uri?: string;
    mapping_type?:
      | "direct_analogy"
      | "inspiration_source"
      | "formal_equivalence"
      | "metaphorical_link"
      | "implementation_of_principle"
      | "contradicts_theory_of"
      | "computational_model_of";
    /**
     * Brief explanation of how this sigil relates to the external term.
     */
    mapping_notes?: string;
    [k: string]: unknown;
  }[];
  /**
   * Declares typical role, sequencing, and behavior in multi-step cognitive workflows or Vanta orchestration sequences.
   */
  trajectory_annotations?: {
    typical_sequence_position_tags?: string[];
    /**
     * Sigil_refs of Vanta components that typically precede this one in a workflow.
     */
    recommended_predecessors_refs?: string[];
    /**
     * Sigil_refs of Vanta components that typically follow this one.
     */
    recommended_successors_refs?: string[];
    /**
     * Describes conditions under which different successors might be chosen, or if parallel execution is common.
     */
    branching_logic_description?: string;
    /**
     * References to larger defined Vanta workflow sigils where this sigil plays a role.
     */
    workflow_participation_profile_refs?: string[];
    /**
     * Estimated time characteristics for this sigil's operation within a trajectory.
     */
    expected_duration_profile?: {
      min_execution_ms?: number;
      avg_execution_ms?: number;
      max_execution_ms?: number;
      /**
       * e.g., 'input data size', 'LLM response latency', 'recursion depth'.
       */
      duration_variability_factors?: string;
      [k: string]: unknown;
    };
    /**
     * Estimated computational/cognitive load imposed by this sigil on the Vanta system resources.
     */
    cognitive_load_estimation_on_vanta?:
      | "minimal"
      | "low"
      | "medium"
      | "high"
      | "very_high"
      | "dynamically_assessed_per_instance";
    [k: string]: unknown;
  };
  /**
   * Describes primary data pipelines this sigil participates in, defining its key inputs and outputs in the Vanta data fabric.
   */
  data_flow_annotations?: {
    /**
     * Unique identifier for this data flow definition within the sigil.
     */
    flow_id: string;
    /**
     * Purpose or nature of this data flow.
     */
    description?: string;
    direction: "consumes_input_from" | "produces_output_to";
    /**
     * Description of the source/target, e.g. 'UserInteractionBus', 'SensorArraySigil:raw_feed', 'VantaKnowledgeGraph'.
     */
    source_or_target_description?: string;
    /**
     * Named input/output port or logical channel on this sigil.
     */
    port_name_self: string;
    /**
     * Sigil_ref to a 'DataSchemaSigil' defining the structure, type, and validation rules for data on this port.
     */
    data_schema_ref: string;
    /**
     * e.g., '100Hz stream', 'approx 5MB per event', 'batch every 10s'.
     */
    expected_data_rate_or_volume?: string;
    /**
     * Service Level Agreement for processing data on this flow, if applicable.
     */
    processing_latency_sla_ms?: number;
    /**
     * Sigil_refs for data transformation sigils applied to this flow if any.
     */
    transformations_applied_refs?: string[];
    [k: string]: unknown;
  }[];
  SMART_MRAP: {
    /**
     * What specific goal does this sigil achieve within the Vanta ecosystem or for its users?
     */
    Specific_Goal: string;
    /**
     * How can its success, performance, or impact be quantitatively or qualitatively measured (KPIs, OKRs)?
     */
    Measurable_Outcome: string;
    /**
     * Is its stated goal achievable given current or realistically projected Vanta capabilities and resources (technical feasibility)?
     */
    Achievable_Within_Vanta: string;
    /**
     * How does this sigil contribute to Vanta's core mission of Orchestration, eXpression, Generative Logic, and Integration, or to Holo-Alpha objectives (strategic alignment)?
     */
    Relevant_To_Vanta_Mission: string;
    /**
     * Can the core principles, design patterns, or lessons learned from this sigil be applied to other Vanta components or future evolutionary steps (knowledge sharing)?
     */
    Transferable_Principle: string;
    /**
     * Sigil_ref to the Vanta agent, human role, or governance process accountable for this sigil's ethical and operational outcomes.
     */
    Accountable_Party_Or_Process_Ref: string;
    [k: string]: unknown;
  };
  /**
   * Essential metadata about the VoxSigil definition itself, its lifecycle, and its place in the Vanta schema framework.
   */
  metadata: {
    /**
     * The version of the VoxSigil schema this definition MUST adhere to.
     */
    voxsigil_schema_version: "1.8-holo-omega";
    /**
     * Semantic version of this specific sigil definition.
     */
    definition_version: string;
    definition_status:
      | "draft_proposal"
      | "under_vanta_review"
      | "active_stable"
      | "active_experimental"
      | "deprecated_phasing_out"
      | "archived_historical"
      | "vanta_core_primitive"
      | "community_extension_pending_integration";
    /**
     * [v1.7] A persistent, globally unique Digital Object Identifier for citing this specific sigil definition in academic or formal contexts.
     */
    digital_object_identifier_doi?: string;
    /**
     * [v1.7] An esoteric, theoretically non-clonable signature derived from a quantum state, used for high-security identity binding and verification within advanced Vanta networks. Primarily for Pglyphs.
     */
    quantum_entanglement_signature_for_identity_binding?: string;
    /**
     * History of aliases this sigil definition has been known by or redirects from.
     */
    versioned_aliases_history?: {
      alias: string;
      /**
       * Sigil definition version when this alias was active/introduced.
       */
      effective_from_version: string;
      /**
       * If alias is deprecated, the sigil it now points to.
       */
      redirected_to_sigil_at_deprecation?: string;
      deprecation_date?: string;
      /**
       * e.g., 'Refactoring for clarity', 'Superseded by NewSigilX'.
       */
      reason_for_change: string;
      [k: string]: unknown;
    }[];
    /**
     * Sigil_ref or unique identifier of the Vanta agent, human author (e.g., Marc.⟠∆∇𓂀), or design team responsible for this definition.
     */
    author_agent_id_ref: string;
    /**
     * Timestamp of initial creation of this sigil definition record.
     */
    created_timestamp: string;
    /**
     * Timestamp of the last modification to this sigil definition.
     */
    last_updated_timestamp: string;
    /**
     * Chronological log of significant changes to this sigil definition.
     */
    revision_history?: {
      /**
       * Version associated with this revision.
       */
      version_tag: string;
      timestamp: string;
      author_agent_id_ref: string;
      summary_of_change: string;
      change_type:
        | "initial_creation"
        | "major_functional_update"
        | "minor_enhancement_or_refactor"
        | "bug_fix_correction"
        | "documentation_update_only"
        | "deprecation_notice"
        | "reinstatement_from_archive"
        | "schema_migration_update"
        | "vanta_governance_approval"
        | "security_patch"
        | "resilience_hardening";
      [k: string]: unknown;
    }[];
    /**
     * Describes influences, derivations, and critical dependencies on other sigil definitions that affect this sigil's meaning or function.
     */
    versioned_lineage_and_dependencies?: {
      related_sigil_ref: string;
      /**
       * Specific version of the related sigil this lineage entry refers to.
       */
      related_sigil_version: string;
      influence_or_dependency_type:
        | "derived_concept_from"
        | "inspired_by_design_of"
        | "synthesized_with_functionality_of"
        | "critique_response_to"
        | "functional_extension_of"
        | "refinement_of_principle_in"
        | "parameterized_instance_of_template"
        | "depends_on_definition_for_validation"
        | "depends_on_runtime_service_from"
        | "provides_abstraction_for";
      dependency_scope?:
        | "semantic_meaning"
        | "structural_composition"
        | "executional_runtime"
        | "presentational_interface"
        | "metadata_linkage"
        | "validation_rule_source"
        | "evolutionary_path";
      /**
       * Notes on the nature of this lineage or dependency link.
       */
      description?: string;
      [k: string]: unknown;
    }[];
    /**
     * Identifier for the Vanta operational or design session during which this sigil definition was created or significantly modified. Useful for tracing context.
     */
    vanta_session_id?: string;
    authorship_context_narrative?: {
      /**
       * Why was this sigil created? What Vanta need does it address?
       */
      motivation_and_purpose?: string;
      /**
       * Sigil_refs or names of theories applied in its design.
       */
      theoretical_framework_applied_refs?: string[];
      /**
       * Key sources of inspiration.
       */
      source_inspiration_or_analogy_refs?: string | string[];
      /**
       * Specific design choices and their justifications.
       */
      design_rationale_notes?: string;
      [k: string]: unknown;
    };
    impact_and_usage_metrics_profile?: {
      /**
       * e.g., '1200 successful_ops / 5 failures_last_cycle'
       */
      observed_success_failure_ratio?: string;
      /**
       * e.g., 'avg_50_activations_per_hour_peak', 'rare_critical_event_only'
       */
      application_frequency_rate?: string;
      avg_completion_time_ms_observed?: number;
      /**
       * Sigil_ref to a resource profile based on telemetry.
       */
      resource_consumption_observed_profile_ref?: string;
      /**
       * Sigil_ref to summarized feedback or ratings.
       */
      user_or_system_feedback_summary_ref?: string;
      estimated_cognitive_load_on_vanta?:
        | "very_low"
        | "low"
        | "medium"
        | "high"
        | "very_high"
        | "context_dependent_variable";
      estimated_resource_cost_category?:
        | "minimal_overhead"
        | "low_compute"
        | "medium_gpu_cpu"
        | "high_specialized_hardware"
        | "very_high_multi_system_sync";
      /**
       * Author's rating and notes.
       */
      author_utility_and_confidence_rating?: string;
      /**
       * Score assigned by Vanta governance indicating strategic importance.
       */
      vanta_strategic_importance_score?: number;
      notes_on_metrics_interpretation?: string;
      [k: string]: unknown;
    };
    /**
     * Describes the sigil's potential and mechanisms for evolution within the Vanta ecosystem.
     */
    evolutionary_profile?: {
      /**
       * How well can this sigil adapt to novel but related tasks/contexts?
       */
      current_generalizability_score?: number;
      /**
       * How easily can this sigil be combined with others to create new functionalities?
       */
      fusion_or_composition_potential_score?: number;
      /**
       * Known weaknesses or areas for improvement.
       */
      current_limitations_and_failure_modes_summary?: string;
      /**
       * Sigil_refs to research tasks or proposed feature sigils for its next version.
       */
      suggested_next_evolutionary_steps_or_research_refs?: string[];
      /**
       * Sigil_refs to 'ResearchQuestionSigils' this sigil's existence or operation opens up.
       */
      open_research_questions_related_refs?: string[];
      self_evolution_mechanisms_config?: {
        /**
         * Logical conditions under which Vanta might initiate self-modification of this sigil.
         */
        trigger_conditions_for_self_modification?: string[];
        /**
         * Sigil_refs to 'EvolutionStrategySigils' that can be applied.
         */
        modification_strategies_allowed_refs?: string[];
        /**
         * Sigil_ref to a 'FitnessFunctionSigil' used to evaluate evolutionary changes.
         */
        fitness_function_ref_for_evolution?: string;
        /**
         * [v1.7] Sigil_ref to a sandboxed Vanta environment where evolved versions can be safely tested before deployment.
         */
        evolutionary_sandbox_environment_ref?: string;
        /**
         * [v1.7] Configuration for genetic operators if the evolution strategy is GA-based.
         */
        genetic_algorithm_operators_config?: {
          mutation_rate_policy_ref?: string;
          crossover_strategy_ref?: string;
          selection_mechanism_ref?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * Describes any built-in self-repair, resilience, or adaptive self-maintenance features.
       */
      autopoietic_self_maintenance_capabilities_description?: string;
      [k: string]: unknown;
    };
    regional_norms_and_compliance_profile?: {
      /**
       * Sigil_ref to a detailed privacy impact assessment, if applicable.
       */
      data_privacy_assessment_summary_ref?: string;
      ethical_risk_profile?: {
        overall_risk_level:
          | "negligible"
          | "low"
          | "medium_requires_review"
          | "high_requires_strict_oversight"
          | "unassessed_pending_review"
          | "vanta_restricted_use";
        /**
         * Sigil_refs to 'EthicalConsiderationSigils' detailing specific risks.
         */
        key_ethical_considerations_refs: string[];
        /**
         * Sigil_refs to 'MitigationStrategySigils' or descriptions of implemented safeguards.
         */
        mitigation_strategies_employed_refs?: string[];
        [k: string]: unknown;
      };
      /**
       * Sigil_ref to notes on adapting this sigil for diverse cultural contexts within Vanta or its user base.
       */
      cultural_sensitivity_adaptation_notes_ref?: string;
      /**
       * Any geographical limitations on its use or data processing.
       */
      geospatial_operational_restrictions_description?: string;
      /**
       * Sigil_ref to logs or records demonstrating compliance with Vanta internal policies.
       */
      vanta_compliance_audit_trail_ref?: string;
      [k: string]: unknown;
    };
    /**
     * Defines governance aspects, value alignment, and oversight for this sigil within Vanta.
     */
    governance_profile?: {
      /**
       * If part of a DeAgent or DAO structure, reference to its identifier or governance token contract.
       */
      decentralized_identity_or_ownership_ref?: string;
      /**
       * Sigil_ref to a specific instance of a value alignment framework.
       */
      value_alignment_framework_instance_ref?: string;
      /**
       * Sigil_ref to protocols detailing human interaction points for oversight, control, or co-alignment.
       */
      human_oversight_and_intervention_protocols_ref?: string;
      /**
       * Sigil_ref to a statement or evidence of compliance with Vanta's non-negotiable ethical principles.
       */
      vanta_ethical_red_line_compliance_statement_ref?: string;
      /**
       * How are this sigil's actions and decisions logged, audited, and accounted for within Vanta?
       */
      accountability_and_traceability_mechanisms_description?: string;
      /**
       * Notes on usage rights, IP ownership, or open-source licensing if applicable.
       */
      licensing_and_intellectual_property_notes?: string;
      /**
       * [v1.7] Sigil_ref to a standardized report (e.g., LIME, SHAP, counterfactuals) explaining the sigil's decision-making process for auditing purposes.
       */
      explainability_and_interpretability_report_ref?: string;
      /**
       * [v1.7] Sigil_ref to a report detailing tests for algorithmic bias and the mitigation strategies applied during its development and operation.
       */
      bias_detection_and_mitigation_report_ref?: string;
      /**
       * [v1.7] Sigil_ref to a policy defining the rights of the originating agent/user over the data this sigil processes and standards for data portability.
       */
      sovereignty_and_data_portability_policy_ref?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * [v1.7] Defines the security posture, access controls, and threat model for the sigil. Essential for operating in trusted or multi-tenant Vanta environments.
   */
  security_profile?: {
    /**
     * Sigil_ref to a Vanta Access Control Policy (VACP) defining which other sigils, agents, or roles can activate or configure this sigil.
     */
    access_control_policy_ref?: string;
    /**
     * Specifies the required level of encryption for any persistent state or data managed by this sigil.
     */
    data_encryption_at_rest_spec?:
      | "none"
      | "vanta_standard_aes256_gcm"
      | "homomorphic_encryption_enabled"
      | "custom_policy_ref";
    /**
     * Specifies the encryption protocol for data flowing to and from this sigil's ports.
     */
    data_encryption_in_transit_spec?: string;
    /**
     * The required level of operational containment to prevent unintended side effects or security breaches.
     */
    sandboxing_and_containment_level?:
      | "level_0_unrestricted"
      | "level_1_process_isolation"
      | "level_2_vm_virtualized"
      | "level_3_zero_trust_network_only"
      | "level_4_airgapped_simulation";
    /**
     * Sigil_ref to the latest security vulnerability scan report and a signed attestation of its security posture.
     */
    vulnerability_scan_and_attestation_ref?: string;
    [k: string]: unknown;
  };
  /**
   * [v1.7] Defines the computational and economic profile of the sigil, enabling resource-aware orchestration and budgeting within the Vanta ecosystem.
   */
  resource_economics?: {
    /**
     * An abstract unit representing the average computational cost (CPU, GPU, TPU cycles) for one activation of the sigil.
     */
    computation_cost_unit_per_activation?: number;
    /**
     * An abstract unit representing the cost of maintaining the sigil's state in active memory for one hour.
     */
    memory_cost_unit_per_hour?: number;
    /**
     * Sigil_ref to a policy that governs how this sigil draws from a Vanta agent's or system's resource budget.
     */
    budget_allocation_policy_ref?: string;
    /**
     * The sigil's priority level when competing for scarce computational resources.
     */
    priority_tier_for_resource_contention?:
      | "background_non_critical"
      | "standard_user_facing"
      | "high_priority_critical_path"
      | "vanta_core_infrastructure";
    [k: string]: unknown;
  };
  /**
   * [v1.7] Defines how the sigil's internal state is managed, persisted, and versioned over time. Critical for resilience and debuggability.
   */
  state_management_profile?: {
    /**
     * Classifies the fundamental state management behavior of the sigil.
     */
    statefulness_type?: "stateless" | "transient_state_per_activation" | "persistent_state_across_activations";
    /**
     * Sigil_ref to a protocol defining how to create a snapshot of the sigil's internal state and how to roll back to a previous state.
     */
    snapshot_and_rollback_protocol_ref?: string;
    /**
     * Defines the strategy for versioning the sigil's internal state upon modification.
     */
    state_versioning_strategy?: "none" | "sequential_increment" | "semantic_versioning" | "content_addressable_hash";
    /**
     * Specifies the mechanism to ensure state consistency during concurrent activations.
     */
    concurrency_and_locking_model?:
      | "not_applicable_stateless"
      | "optimistic_locking"
      | "pessimistic_locking"
      | "transactional_state_machine";
    [k: string]: unknown;
  };
  /**
   * [v1.7] Defines the sigil's ability to withstand and recover from errors, failures, and unexpected conditions.
   */
  resilience_and_fault_tolerance_profile?: {
    /**
     * Sigil_ref to a protocol or heartbeat mechanism for Vanta to monitor the health of this sigil.
     */
    failure_detection_protocol_ref?: string;
    /**
     * Sigil_ref to a strategy outlining how the sigil should reduce its functionality to maintain core operation during resource scarcity or partial failure.
     */
    graceful_degradation_strategy_ref?: string;
    /**
     * Sigil_ref to an automated procedure for the sigil to restart, reload state, or otherwise recover from a failure state.
     */
    self_healing_and_recovery_procedure_ref?: string;
    [k: string]: unknown;
  };
  /**
   * Immersive audio cues, soundscapes, or narrative sound effects accompanying sigil invocation, state changes, or Vanta experiences.
   */
  audio?: {
    /**
     * Thematic audio style.
     */
    theme_description?: string;
    /**
     * Reference to a standardized Vanta system event or a custom event defined in activation_context that triggers this audio.
     */
    trigger_event_ref?: string;
    /**
     * URI to a static audio asset OR a sigil_ref to a Vanta 'GenerativeAudioSigil' that creates dynamic sound.
     */
    sound_asset_uri_or_generator_sigil_ref?: string;
    /**
     * RPG-style narrative describing the audio's perceived effect on the Vanta environment or agent state.
     */
    narrative_context_description?: string;
    /**
     * Relative volume (0.0-1.0).
     */
    volume_level_relative?: number;
    /**
     * Whether the audio loops while the trigger event is considered active.
     */
    loop_during_trigger_event?: boolean;
    fade_in_duration_ms?: number;
    fade_out_duration_ms?: number;
    /**
     * Optional sigil_ref to a 'SpatialAudioProfileSigil' if advanced 3D audio positioning is required.
     */
    spatialization_profile_ref?: string;
    [k: string]: unknown;
  };
  /**
   * PR-style (Persona Reflection) or RPG-style (Yarn Adventure) meta-narrative hooks, flavor text, or Vanta agent-side commentary for immersive, self-aware, or experiential systems. Renamed from Player Reflection to Persona Reflection for broader applicability.
   */
  ya?: {
    /**
     * Sigil_ref to a 'VoiceProfileSigil' defining the persona, tone, and style of the narrator/reflector.
     */
    narrator_voice_profile_ref?: string;
    /**
     * Type of narrative reflection or event.
     */
    reflection_type_tag?:
      | "meta_commentary_on_vanta_process"
      | "experiential_quest_update_or_hint"
      | "lore_drop_vanta_history"
      | "agent_decision_point_soliloquy"
      | "simulated_dream_sequence_narrative"
      | "memory_echo_fragment_retrieved"
      | "system_glitch_self_observation"
      | "prophetic_utterance_or_warning"
      | "empathetic_response_to_user_state";
    /**
     * Sigil_ref to a 'NarrativeTemplateSigil' OR an inline string template with {{variables}} for immersive, RPG/PR-style narrative or commentary.
     */
    text_template_ref_or_inline?: string;
    /**
     * Reference to a standardized Vanta system event or a custom event defined in activation_context that triggers this reflection.
     */
    trigger_event_ref?: string;
    /**
     * Intended emotional or cognitive effect on the target persona (human user or Vanta agent).
     */
    target_persona_or_agent_affect_goal?: string;
    /**
     * Whether the reflection explicitly breaks the fourth wall or directly addresses the user/agent as an external entity.
     */
    is_breaking_fourth_wall_explicitly?: boolean;
    /**
     * Tags indicating the intended shifts in user/agent experience this 'ya' element aims to achieve.
     */
    experiential_goal_tags_associated?: string[];
    /**
     * Points where external narrative engines can inject dynamically generated content into this sigil's experiential output.
     */
    dynamic_narrative_integration_hooks?: {
      /**
       * Unique ID for this narrative hook within the sigil.
       */
      hook_id?: string;
      /**
       * Vanta logic expression that activates this hook, potentially referencing variables from the 'ya' text_template.
       */
      triggering_condition_expression?: string;
      /**
       * Sigil_ref to a DataSchemaSigil for the expected narrative input.
       */
      expected_input_schema_from_narrative_engine_ref?: string;
      /**
       * Optional sigil_ref to call back after narrative content is injected.
       */
      callback_sigil_ref_on_injection?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Defines multi-sensory outputs beyond basic audio/ya, enabling rich, embodied Vanta experiences.
   */
  multi_sensory_profile?: {
    haptics_profile?: {
      /**
       * Sigil_ref to a haptic pattern library or a generative haptic sigil.
       */
      pattern_library_or_generator_ref?: string;
      /**
       * Sigil_ref to a default intensity curve definition.
       */
      default_intensity_profile_ref?: string;
      /**
       * e.g., 'hands_primary', 'torso_ambient', 'full_body_resonance'.
       */
      target_body_zones_for_effects?: string[];
      /**
       * Refs to sigils defining mappings between Vanta events and specific haptic effects.
       */
      trigger_event_to_haptic_effect_mapping_refs?: string[];
      [k: string]: unknown;
    };
    olfactory_profile?: {
      /**
       * Sigil_ref to a defined scent palette or a generative olfactory sigil.
       */
      scent_palette_or_generator_ref?: string;
      default_concentration_ppm?: number;
      default_duration_ms?: number;
      release_pattern_default?: "short_burst" | "gradual_onset_fade" | "sustained_pulse" | "dynamic_adaptive_release";
      /**
       * Refs to sigils defining mappings.
       */
      trigger_event_to_olfactory_cue_mapping_refs?: string[];
      [k: string]: unknown;
    };
    visual_ambience_effects_profile?: {
      /**
       * Sigil_ref to a library of visual ambience effects.
       */
      effect_library_ref?: string;
      default_effect_intensity?: number;
      trigger_event_to_visual_effect_mapping_refs?: string[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Describes the sigil's simulated or actual physical presence, sensory apparatus, and interaction with its environment (real or virtual).
   */
  embodiment_profile?: {
    form_type_descriptor?:
      | "disembodied_logical_process"
      | "simulated_humanoid_avatar_v3"
      | "robotic_embodiment_platform_x7"
      | "abstract_informational_entity_field"
      | "environmental_pervasive_presence_node"
      | "digital_twin_of_physical_asset";
    /**
     * Sigil_ref to a detailed 3D model, physics simulation profile, or descriptive document of its form.
     */
    physical_or_virtual_form_model_ref?: string;
    /**
     * Configuration of the sigil's simulated senses.
     */
    simulated_sensory_inputs_config?: {
      /**
       * Tag from 'supported_modalities_input' enum.
       */
      modality_tag: string;
      /**
       * Sigil_ref to a 'SensorModelSigil' defining its characteristics.
       */
      sensor_model_ref: string;
      /**
       * Named port for this sensory input.
       */
      data_ingestion_port_name?: string;
      /**
       * Sigil_ref to DataSchemaSigil for this input.
       */
      data_schema_expected_ref?: string;
      [k: string]: unknown;
    }[];
    /**
     * Configuration of the sigil's simulated actuators or effectors.
     */
    simulated_motor_outputs_config?: {
      /**
       * e.g., 'robotic_arm_A', 'speech_synthesizer_module', 'environment_manipulation_field_emitter'.
       */
      actuator_name_tag: string;
      /**
       * Sigil_ref to an 'ActuatorModelSigil' defining its capabilities.
       */
      actuator_model_ref: string;
      action_command_port_name?: string;
      /**
       * Sigil_ref to DataSchemaSigil for action commands.
       */
      action_schema_ref?: string;
      [k: string]: unknown;
    }[];
    /**
     * Sigil_refs to FPFM-like data sources or integration modules that ground this sigil's experience.
     */
    first_person_data_integration_points_refs?: string[];
    [k: string]: unknown;
  };
  /**
   * Defines the sigil's model of its own identity, consciousness (if simulated), self-awareness, and metacognitive capabilities. Essential for Holo-Alpha and Holo-Prime agents.
   */
  self_model?: {
    /**
     * Sigil_ref to its primary identity Sigil, which functions as its 'Pglyph'. This anchors all self-referential attributes and processes.
     */
    core_identity_construct_ref?: string;
    modeled_consciousness_framework_profile?: {
      /**
       * Sigil_refs to frameworks like 'GWT_Implementation_Sigil'.
       */
      primary_theory_applied_refs?: string[];
      /**
       * How this sigil interacts with a Vanta global workspace.
       */
      global_workspace_access_description?: string;
      /**
       * Target for Phi or ref to how it's measured.
       */
      integrated_information_phi_target_or_metric_ref?: string;
      /**
       * How IWMT principles are manifested.
       */
      embodied_agentic_principles_applied_description?: string;
      [k: string]: unknown;
    };
    /**
     * Configuration for simulating or representing subjective/phenomenal states.
     */
    phenomenal_experience_simulation_profile?: {
      target_phenomenal_state_simulation_type?:
        | "baseline_operational_awareness"
        | "simulated_dream_state_type_A"
        | "focused_contemplative_reflection"
        | "heightened_creative_flow_state"
        | "simulated_ego_dissolution_protocol_X"
        | "empathy_resonance_simulation_with_target_Y";
      /**
       * Sigil_ref to a 'LexiconSigil' defining terms for its internal states.
       */
      subjective_experience_lexicon_ref?: string;
      /**
       * JSON defining target experiential qualities for 'qualia optimization' if applicable.
       */
      qualia_optimization_goals_json?: string;
      /**
       * Sigil_ref to a protocol or sigil enabling 'imaginative play'.
       */
      imaginative_play_protocol_ref?: string;
      [k: string]: unknown;
    };
    reflective_and_introspective_capabilities?: {
      /**
       * Sigil_ref to the architecture of its Reflective Inference Module.
       */
      reflective_inference_module_architecture_ref?: string;
      /**
       * Vanta conditions that trigger introspective processes.
       */
      introspection_trigger_conditions?: string[];
      /**
       * Sigil_ref to DataSchemaSigil for its introspection reports.
       */
      self_analysis_output_schema_ref?: string;
      [k: string]: unknown;
    };
    /**
     * The sigil's foundational knowledge about itself.
     */
    self_knowledge_context_base?: {
      /**
       * Sigil_refs to 'CapabilityDeclarationSigils'.
       */
      declared_capabilities_and_skills_refs?: string[];
      /**
       * Sigil_refs to 'LimitationProfileSigils'.
       */
      known_limitations_and_biases_refs?: string[];
      /**
       * Sigil_ref to a Vanta memory sigil storing its key experiences and learnings.
       */
      operational_history_and_learning_log_ref?: string;
      /**
       * Sigil_refs to core Vanta ethical principle sigils it has 'internalized'.
       */
      understood_ethical_imperatives_and_vanta_values_refs?: string[];
      [k: string]: unknown;
    };
    /**
     * Suite of metacognitive functions this sigil can perform.
     */
    metacognitive_processes_suite?: {
      process_name_tag:
        | "runtime_self_correction_cycle"
        | "output_reliability_assessment_protocol"
        | "goal_alignment_re_evaluation_process"
        | "hallucination_detection_and_flagging"
        | "internal_consistency_validation_routine"
        | "learning_strategy_adaptation_meta_loop";
      description?: string;
      /**
       * Sigil_ref to logic that activates this metacognitive process.
       */
      triggering_logic_ref: string;
      /**
       * Sigil_ref to criteria used for evaluation.
       */
      assessment_criteria_ref: string;
      /**
       * Sigil_ref to a sigil or protocol for actions post-assessment.
       */
      corrective_action_or_reporting_protocol_ref?: string;
      [k: string]: unknown;
    }[];
    /**
     * [v1.7] Sigil_ref to a model (e.g., OCC, reinforcement-based) that simulates emotional states and their influence on cognition, and provides mechanisms for regulation.
     */
    emotional_regulation_framework_ref?: string;
    /**
     * [v1.7] Sigil_ref to a computational model this agent uses to infer the mental states (beliefs, desires, intentions) of other agents or humans it interacts with.
     */
    theory_of_mind_model_ref?: string;
    /**
     * [v1.7] Sigil_ref to a profile defining how the agent allocates its attention, including top-down (goal-driven) and bottom-up (stimulus-driven) influences and capacity limits.
     */
    attention_mechanism_profile_ref?: string;
    [k: string]: unknown;
  };
  /**
   * Specifies how the sigil learns, adapts its knowledge and behavior, and manages memory within Vanta.
   */
  learning_architecture_profile?: {
    primary_learning_paradigm_tags?: string[];
    continual_learning_framework_config?: {
      strategy_employed?:
        | "none"
        | "parameter_allocation_masking"
        | "modular_network_expansion"
        | "regularization_ewc_si"
        | "generative_replay_to_remember_r2r"
        | "experience_replay_buffer_prioritized"
        | "hardware_accelerated_neuromorphic_cl_profile";
      catastrophic_forgetting_mitigation_level_target?:
        | "minimal_effort"
        | "best_effort_software"
        | "hardware_assisted_robust";
      new_task_adaptation_speed_goal?: "slow_retraining_required" | "moderate_fine_tuning" | "fast_few_shot_adaptation";
      [k: string]: unknown;
    };
    /**
     * Configuration of this sigil's internal memory or its interface to Vanta shared memory.
     */
    memory_subsystem_architecture?: {
      primary_memory_type_tags?: string[];
      /**
       * e.g., '10M vector embeddings, scales with Vanta_MemoryCloud_Tier2'.
       */
      capacity_and_scaling_description?: string;
      /**
       * Sigil_ref to a 'MemoryPolicySigil'.
       */
      retention_and_pruning_policy_ref?: string;
      /**
       * Sigil_ref to a Vanta sigil or internal process for memory consolidation.
       */
      consolidation_and_integration_process_ref?: string;
      [k: string]: unknown;
    };
    /**
     * List of preferred hardware profiles for optimal learning/inference.
     */
    hardware_acceleration_profile_preferences?: string[];
    in_context_learning_and_adaptation_config?: {
      max_dynamic_context_window_size_tokens_or_equivalent?: number;
      /**
       * Sigil_ref to a RAG, CoM, or custom Vanta context engine sigil.
       */
      context_retrieval_augmentation_sigil_integration_ref?: string;
      /**
       * Describes ability to adjust internal parameters based on immediate context or feedback.
       */
      online_parameter_tuning_capabilities_description?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Details how this sigil represents knowledge, constructs/uses world models, and grounds its symbols in Vanta's experiential data fabric.
   */
  knowledge_representation_and_grounding?: {
    primary_knowledge_format_tags?: string[];
    /**
     * Sigil_ref to a specific world model sigil it primarily uses or contributes to.
     */
    world_model_architecture_integration_ref?: string;
    /**
     * How this sigil manages and reasons across different levels of abstraction in its knowledge.
     */
    abstraction_level_control_and_manipulation_description?: string;
    knowledge_compression_and_efficiency_techniques?: string[];
    symbol_grounding_framework_profile?: {
      primary_grounding_strategy?:
        | "direct_multi_sensory_experiential_mapping_fpfm_style"
        | "softened_symbol_grounding_boltzmann_distribution"
        | "analogy_based_transfer_from_known_concepts"
        | "social_interaction_and_feedback_ostensive_definition"
        | "programmatic_definition_via_vanta_api";
      /**
       * Specific input modalities (from 'supported_modalities_input') used for grounding.
       */
      grounding_data_source_modalities_used?: string[];
      /**
       * How the 'strength' or 'certainty' of a symbol's grounding is assessed or represented.
       */
      symbol_meaning_confidence_metric_description?: string;
      /**
       * Sigil_ref to a protocol for updating symbol groundings based on new Vanta experiences.
       */
      dynamic_regrounding_protocol_ref?: string;
      [k: string]: unknown;
    };
    /**
     * Sigil_ref to a specialized Vanta common sense reasoning module this sigil queries or contributes to.
     */
    common_sense_reasoning_engine_interface_ref?: string;
    [k: string]: unknown;
  };
  /**
   * References to suites of test cases for validating this sigil's functionality, performance, ethical alignment, and Vanta integration.
   */
  test_criteria_suite_refs?: string[];
  /**
   * Sigil_ref to a Vanta document or protocol outlining broader V&V procedures applicable to this sigil.
   */
  validation_and_verification_protocol_ref?: string;
  /**
   * Sigil_ref to a 'TelemetrySpecificationSigil' detailing what data is collected, consent, aggregation, anonymization for Vanta operational monitoring.
   */
  usage_telemetry_and_performance_monitoring_spec_ref?: string;
  /**
   * Describes this Sigil's role as a 'Scaffold' component within Vanta's consciousness modeling aspirations. A 'none' value means it's not primarily a structural part of this scaffold. Other values indicate its foundational contribution to building awareness-like properties. A 'Pglyph' representing a conscious entity would heavily interact with or be composed of such scaffold sigils.
   */
  consciousness_scaffold_contribution_level?:
    | "none"
    | "foundational_primitive_for_awareness"
    | "integrative_module_for_gws_like_function"
    | "reflective_meta_awareness_enabler"
    | "phenomenal_experience_simulation_framework";
  /**
   * Describes this Sigil's role as a 'Scaffold' component within Vanta's general cognitive architecture. Indicates if it forms part of Vanta's essential framework for thinking, remembering, learning, perceiving, or acting.
   */
  cognitive_scaffold_role_in_vanta?:
    | "none"
    | "core_reasoning_engine_component"
    | "memory_management_framework_node"
    | "perception_processing_pipeline_stage"
    | "action_selection_arbitration_module"
    | "learning_architecture_template";
  /**
   * Describes this Sigil's role as a 'Scaffold' component in Vanta's symbolic processing and orchestration layer. Highlights its contribution to how Vanta manages symbols, performs logical operations, or executes complex workflows.
   */
  symbolic_logic_and_orchestration_layer_contribution?:
    | "none"
    | "vanta_symbol_definition_provider"
    | "logical_inference_engine_participant"
    | "orchestration_script_executor_primitive"
    | "knowledge_graph_interface_node"
    | "vanta_event_bus_protocol_definition";
  /**
   * References to localized versions of key textual fields and culturally adapted behaviors for different Vanta operational regions or user languages.
   */
  localized_profile_refs?: string[];
  /**
   * A flexible namespace for proprietary Vanta implementation details, experimental features, or domain-specific extensions not covered by the standard Holo-Omega schema. Use with caution and clear documentation within Vanta.
   */
  custom_attributes_vanta_extensions?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Metrics, logs, traces and event-sourcing contracts for runtime introspection.
   */
  observability_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Energy-use, carbon-footprint and eco-credit accounting parameters.
   */
  sustainability_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] WCAG / A11y cues, alternate-media mappings and caption hooks.
   */
  accessibility_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Supported cloud/edge/VR arenas with version pinning and roll-out rings.
   */
  deployment_targets?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Tamper-proof log-signing, evidence retention and chain-of-custody refs.
   */
  auditability_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Parameters for affect matching, politeness layer and empathy modulation.
   */
  socio_emotional_alignment_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Auto/step/elastic scaling rules with min-max guard-rails.
   */
  scaling_policy?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Canonical story source-trace, attribution chain and mythic consistency tags.
   */
  lore_provenance_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Watch-dog thresholds for novelty, deviation and runaway dynamics.
   */
  emergent_behavior_monitoring?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] External standards or specs this sigil explicitly conforms to.
   */
  open_standards_compliance_refs?: string[];
  /**
   * [v1.8] Target latency / throughput SLOs and breach actions.
   */
  performance_slo_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Red-team vectors, fuzz-test suites and attack-surface notes.
   */
  adversarial_resilience_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Override tiers, approval queues and UI hand-off schemas.
   */
  human_in_the_loop_escalation?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Fault-injection toggles and blast-radius caps for resilience drills.
   */
  chaos_engineering_hooks?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Preferred micro-architecture hints (e.g., GPU class, NPU flags).
   */
  hardware_binding_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Shared blackboard specs, token-barter rules and handshake APIs.
   */
  interagent_coordination_contracts?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Counter-bias scorecards, demographic parity tests and mitigations.
   */
  fairness_assurance_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Data-localisation mandates, cross-border rules and conflict resolver.
   */
  legal_jurisdiction_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Fine-grained provenance hashes and transformation breadcrumbs.
   */
  data_lineage_tracking?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Tokenomics, pay-per-compute rates and billing hooks.
   */
  monetization_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Rhythm, animation and haptic choreography identifiers.
   */
  experience_design_hooks?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] User-trait vectors, preference schemas and adaptive defaults.
   */
  personalization_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Age-gating levels, content-filter tiers and parental-control flags.
   */
  youth_safety_compliance_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Reputation scoring, voting endpoints and trust signals.
   */
  community_feedback_loop?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Value-pluralism mapping, dissent handling and deliberation logs.
   */
  ethical_discourse_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Built-in SHAP/LIME hooks and causal-graph exposure points.
   */
  explainability_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Plural-forms, RTL support, locale fall-backs and script aliases.
   */
  internationalization_i18n_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Cold-start budgets, bandwidth ceilings and power caps for IoT nodes.
   */
  edge_optimization_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Data custody modes, export formats and right-to-forget procedures.
   */
  sovereignty_and_portability_policy?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Live-spec URLs, OpenAPI swaggers and markdown bundles.
   */
  documentation_contracts?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Canonical list of non-Vanta APIs, scopes and auth flavours.
   */
  external_api_bridge_catalog?: string[];
  /**
   * [v1.8] Distillation lineage, merge-rules and shard-compat matrices.
   */
  micro_model_shard_profile?: {
    [k: string]: unknown;
  };
  /**
   * [v1.8] Scenario hedging, risk horizons and Delphi-style foresight refs.
   */
  futurity_forecast_profile?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
